### ISSUE TITLE
Xiaomi Redmi 4 - not working

### ISSUE THREAD

**Issue by AndreiMisiukevich** [alexrainman/Badge#1]
Hello, Alexander.
Thanks for your job.
I have an issue with Xiaomi Redmi 4 (There is no badge)
I tested on Sony XPeria and there it was.

Could you provide me any advice or this device type isn't supported?

Best regards

**Comment by alexrainman** [comment]
I don't have that device to test :(

**Comment by jmalmor** [comment]
Don't work. I add the permissions and set in many parts of my code to add a number to badge. I am missing something? I put on almost any event and on applications point as start, resume, manual events, push in message event, no of these seems to work. I am missing something that is not in the documentation?

**Comment by alexrainman** [comment]
The thing is i don't have a Xiaomi 4 device for testing. Badge API is different in all Android devices.
