### ISSUE TITLE
In xamarin android, when app is closed then badge count is not updating

### ISSUE THREAD

**Issue by nrb1238** [alexrainman/Badge#3]
Hi @alexrainman 

i am trying to update the badge count when ever i get the push notification. when app is open then it working but when app is closed the badge count is not updating(push notification is receiving when is app closed) 

 public class MyGcmListenerService : GcmListenerService
    {
        public override void OnMessageReceived(string from, Bundle data)
        {
         CrossBadge.Current.SetBadge(10);
         }
}

**Comment by alexrainman** [comment]
Use a background service for this.
